services:
  mongoDatabase:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: backend-challenge
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "secret", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongoDatabase:
        condition: service_healthy
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    ports:
      - '8080:8080'
